#!/bin/bash

OPKG_CMD_PREFIX="opkg install --force-depends ./provisioning/"
OPKG_CMD_PREFIX_R="opkg remove --force-depends "
MANIFEST="./provisioning/p_manifest.json"
NAME="Install"

function install_packages {
    if [ ! -f "$MANIFEST" ]; then
        return
    fi
    JSONTXT=$(<./provisioning/p_manifest.json)
    PKGCNT=$(echo $JSONTXT | jsparser --count -p /pkgs)
    RETURNCODE=$?
    if [ $RETURNCODE -ne 0 ]; then
      echo "Failed to parse p_manifest.json as json"
      exit $RETURNCODE
    fi
    for ((i=0; i < PKGCNT; i++))
    do
        PKG=$(echo $JSONTXT | jsparser --jsobj -p /pkgs/$i)
        PKGNM=$(echo $PKG | jsparser -p /FileName)
        PKGTYPE=$(echo $PKG | jsparser -p /type)
        if [ "$PKGTYPE" == "ipk" ]; then
            PKGCMD=$OPKG_CMD_PREFIX$PKGNM
            echo "Executing: $PKGCMD"
            eval $PKGCMD
            if [ $? != 0 ]; then
                echo "Command [$PKGCMD] failed with status $?"
                logger -t Install "Command [$PKGCMD] failed with status $?"
                exit $?
            fi
        fi
        logger -t Install "Command [$PKGCMD] succeeded"
    done
}

function post_install {
    echo "post_install"
}

function remove_packages {
    if [ ! -f "$MANIFEST" ]; then
        echo "provisioning manifest file not found"
        return
    fi
    JSONTXT=$(<./provisioning/p_manifest.json)
    PKGCNT=$(echo $JSONTXT | jsparser --count -p /pkgs)
    RETURNCODE=$?
    if [ $RETURNCODE -ne 0 ]; then
      echo "Failed to parse p_manifest.json as json"
      exit $RETURNCODE
    fi
    for ((i=0; i < PKGCNT; i++))
    do
        PKG=$(echo $JSONTXT | jsparser --jsobj -p /pkgs/$i)
        PKGNM=$(echo $PKG | jsparser -p /PkgName)
        PKGTYPE=$(echo $PKG | jsparser -p /type)
        if [ "$PKGTYPE" == "ipk" ]; then
            PKGCMD=$OPKG_CMD_PREFIX_R$PKGNM
            echo "Executing: $PKGCMD"
            eval $PKGCMD
            if [ $? != 0 ]; then
                echo "Command [$PKGCMD] failed with status $?"
                logger -t Install "Command [$PKGCMD] failed with status $?"
                exit $?
            fi
        fi
        logger -t Install "Command [$PKGCMD] succeeded"
    done
}

function post_remove {
    echo "post_remove"
}

case "$1" in
  install)
      echo -n "Installing dependencies: "
      logger -t Install "Installing Dependencies: "
      install_packages
      echo "$NAME."
      ;;
  remove)
      echo -n "Removing Dependencies: "
      logger -t Install "Removing Dependencies: "
      remove_packages
      echo "$NAME."
      ;;
  postinstall)
      echo -n "Running app post install "
      logger -t Install "Running app post install "
      post_install
      echo "$NAME."
      ;;
  postremove)
      echo -n "Running app post remove "
      logger -t Install "Running app post remove "
      post_remove
      echo "$NAME."
      ;;
  *)
      N=$NAME
      echo "Usage: $N {install|remove|postinstall|postremove}" >&2
      exit 1
      ;;
esac

exit 0
